
version: '3'
services:
  kanban:
    build: .
    environment:
      - REACT_APP_PORT=888
      - REACT_APP_HOST=localhost
    ports:
      - "777:3000"
  server:
    build: server/
    ports:
      - "888:888"

   